"""invite codes

Revision ID: 2b4fc2e830d5
Revises: 20260101000001
Create Date: 2026-08-15 01:05:56.537309
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

import tradeloom.db.types
from alembic import op

revision: str = "2b4fc2e830d5"
down_revision: str | None = "20260101000001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invite_codes",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("note", sa.String(length=160), nullable=True),
        sa.Column("created_by_user_id", tradeloom.db.types.GUID(), nullable=True),
        sa.Column("max_uses", sa.Integer(), nullable=False),
        sa.Column("used_count", sa.Integer(), nullable=False),
        sa.Column("expires_at", tradeloom.db.types.TZDateTime(), nullable=True),
        sa.Column("revoked_at", tradeloom.db.types.TZDateTime(), nullable=True),
        sa.Column("id", tradeloom.db.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            tradeloom.db.types.TZDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            tradeloom.db.types.TZDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_invite_codes_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invite_codes")),
        sa.UniqueConstraint("code", name="uq_invite_codes_code"),
    )
    with op.batch_alter_table("invite_codes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_invite_codes_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "invite_redemptions",
        sa.Column("invite_code_id", tradeloom.db.types.GUID(), nullable=False),
        sa.Column("user_id", tradeloom.db.types.GUID(), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("id", tradeloom.db.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            tradeloom.db.types.TZDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            tradeloom.db.types.TZDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invite_code_id"],
            ["invite_codes.id"],
            name=op.f("fk_invite_redemptions_invite_code_id_invite_codes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_invite_redemptions_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invite_redemptions")),
        sa.UniqueConstraint("user_id", name="uq_invite_redemptions_user"),
    )
    with op.batch_alter_table("invite_redemptions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_invite_redemptions_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index("ix_invite_redemptions_invite", ["invite_code_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("invite_redemptions", schema=None) as batch_op:
        batch_op.drop_index("ix_invite_redemptions_invite")
        batch_op.drop_index(batch_op.f("ix_invite_redemptions_created_at"))

    op.drop_table("invite_redemptions")
    with op.batch_alter_table("invite_codes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_invite_codes_created_at"))

    op.drop_table("invite_codes")
    # ### end Alembic commands ###
