"""feedback reports

Revision ID: 9360b39db86c
Revises: 2b4fc2e830d5
Create Date: 2026-08-15 01:32:09.451304
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

import tradeloom.db.types
from alembic import op

revision: str = "9360b39db86c"
down_revision: str | None = "2b4fc2e830d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback_reports",
        sa.Column("organization_id", tradeloom.db.types.GUID(), nullable=True),
        sa.Column("user_id", tradeloom.db.types.GUID(), nullable=True),
        sa.Column("reporter_email", sa.String(length=320), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("page", sa.String(length=255), nullable=True),
        sa.Column("context", tradeloom.db.types.JSONDict(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reviewed_at", tradeloom.db.types.TZDateTime(), nullable=True),
        sa.Column("reviewed_by_user_id", tradeloom.db.types.GUID(), nullable=True),
        sa.Column("id", tradeloom.db.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            tradeloom.db.types.TZDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            tradeloom.db.types.TZDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_feedback_reports_organization_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
            name=op.f("fk_feedback_reports_reviewed_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_feedback_reports_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback_reports")),
    )
    with op.batch_alter_table("feedback_reports", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_feedback_reports_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index("ix_feedback_reports_org", ["organization_id"], unique=False)
        batch_op.create_index(
            "ix_feedback_reports_status_created", ["status", "created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feedback_reports", schema=None) as batch_op:
        batch_op.drop_index("ix_feedback_reports_status_created")
        batch_op.drop_index("ix_feedback_reports_org")
        batch_op.drop_index(batch_op.f("ix_feedback_reports_created_at"))

    op.drop_table("feedback_reports")
    # ### end Alembic commands ###
