"""policy acceptances

Revision ID: aedd7a7dcecf
Revises: 9360b39db86c
Create Date: 2026-08-15 01:53:30.685427
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

import tradeloom.db.types
from alembic import op

revision: str = "aedd7a7dcecf"
down_revision: str | None = "9360b39db86c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "policy_acceptances",
        sa.Column("user_id", tradeloom.db.types.GUID(), nullable=False),
        sa.Column("document", sa.String(length=24), nullable=False),
        sa.Column("version", sa.String(length=24), nullable=False),
        sa.Column("accepted_at", tradeloom.db.types.TZDateTime(), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=320), nullable=True),
        sa.Column("id", tradeloom.db.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            tradeloom.db.types.TZDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            tradeloom.db.types.TZDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_policy_acceptances_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_acceptances")),
        sa.UniqueConstraint("user_id", "document", "version", name="uq_policy_acceptance"),
    )
    with op.batch_alter_table("policy_acceptances", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_policy_acceptances_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index("ix_policy_acceptances_user", ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("policy_acceptances", schema=None) as batch_op:
        batch_op.drop_index("ix_policy_acceptances_user")
        batch_op.drop_index(batch_op.f("ix_policy_acceptances_created_at"))

    op.drop_table("policy_acceptances")
    # ### end Alembic commands ###
